---
# Installs the AD
# create necessary steps for Active Directory Install
- win_feature:
    name: "AD-Domain-Services"
    include_management_tools: true
    include_sub_features: true
    state: present
- win_feature:
    name: "DNS"
    include_management_tools: true
    include_sub_features: true
    state: present
    reboot: yes
- name: Add AD Forest
  script: install_ad_forest.ps1 {{rootdomain}} {{netbios}} {{ansible_ssh_pass}}
- name: Create Users
  script: add_user.ps1 {{item.value.firstname}} {{item.value.surname}} {{item.value.email}} {{idpfqdn}} {{initialpassword}}
  with_dict: users 

#- include: createoustructure.yml